# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - classtatistics

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/classstatician/
        username: ${{ secrets.AzureAppService_ContainerUsername_671da3d7cdb44c96b9a642b916d1e42e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9fe71faab47d4c319c9753fbf3c69803 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/classstatician/${{ secrets.AzureAppService_ContainerUsername_671da3d7cdb44c96b9a642b916d1e42e }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'classtatistics'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a35afe13076d4f3db8f0bcfea42af3ec }}
        images: 'mcr.microsoft.com/classstatician/${{ secrets.AzureAppService_ContainerUsername_671da3d7cdb44c96b9a642b916d1e42e }}/appsvc/staticsite:${{ github.sha }}'